# backend/serverless.yml

service: kanjisama-api

provider:
  name: aws
  runtime: nodejs22.x
  region: ap-northeast-1
  profile: asdf

  # Configure CORS globally for the HTTP API
  httpApi:
    cors: true # Enables default CORS settings (allows all origins, common methods/headers)
    # For more specific CORS configuration later, you can use:
    # cors:
    #   allowedOrigins:
    #     - 'https://your-amplify-domain.com' # Replace with your actual frontend domain
    #   allowedHeaders:
    #     - Content-Type
    #     - Authorization
    #     # Add other headers as needed
    #   allowedMethods:
    #     - GET
    #   allowCredentials: false
    #   maxAge: 6000

functions:
  queryKanji:
    handler: handler.queryKanji
    events:
      - httpApi:
          path: /query/{term}/{page}
          method: get
      - httpApi:
          path: /query/_/{page} # Placeholder for empty term
          method: get
  proxyJisho:
    handler: handler.proxyJisho
    events:
      - httpApi:
          path: /jisho-proxy/{term}
          method: get

# Plugin for local testing
plugins:
  - serverless-offline